[package]
name = "announcement"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic = "0.5"

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full"] }
